package handler

import (
	"log"
	"net/http"
	"quickdesk/signaling/internal/config"
	"quickdesk/signaling/internal/service"

	"github.com/gin-gonic/gin"
)

type APIHandler struct {
	deviceService *service.DeviceService
	authService   *service.AuthService
	config        *config.Config
	wsHandler     *WSHandler
}

func NewAPIHandler(deviceService *service.DeviceService, authService *service.AuthService, cfg *config.Config) *APIHandler {
	return &APIHandler{
		deviceService: deviceService,
		authService:   authService,
		config:        cfg,
	}
}

// SetWSHandler sets the WebSocket handler reference (called after WSHandler is created)
func (h *APIHandler) SetWSHandler(ws *WSHandler) {
	h.wsHandler = ws
}

// RegisterDevice handles POST /api/v1/devices/register
// Request: { "device_id": "optional", "os": "Windows", "os_version": "11", "app_version": "1.0.0" }
// Response: { "device_id": "123456789", "is_new": true/false }
func (h *APIHandler) RegisterDevice(c *gin.Context) {
	var req service.RegisterDeviceRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request"})
		return
	}
	
	device, isNew, err := h.deviceService.RegisterDevice(c.Request.Context(), &req)
	if err != nil {
		log.Printf("Failed to register device: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to register device"})
		return
	}
	
	// Note: Temporary password is now generated by Host and sent via WebSocket
	// No longer generated here during registration
	
	c.JSON(http.StatusOK, gin.H{
		"device_id": device.DeviceID,
		"is_new":    isNew,
	})
	
	if isNew {
		log.Printf("New device registered: device_id=%s", device.DeviceID)
	} else {
		log.Printf("Existing device verified: device_id=%s", device.DeviceID)
	}
}

// GetDevice handles GET /api/v1/devices/:device_id
func (h *APIHandler) GetDevice(c *gin.Context) {
	deviceID := c.Param("device_id")
	
	device, err := h.deviceService.GetByDeviceID(c.Request.Context(), deviceID)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "device not found"})
		return
	}
	
	c.JSON(http.StatusOK, device)
}

// VerifyPassword handles POST /api/v1/auth/verify
// Request: { "device_id": "123456789", "password": "654321" }
// Response: { "valid": true, "connection_token": "..." } or { "valid": false, "error": "HOST_OFFLINE" }
func (h *APIHandler) VerifyPassword(c *gin.Context) {
	var req struct {
		DeviceID string `json:"device_id" binding:"required"`
		Password string `json:"password" binding:"required"`
	}
	
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request"})
		return
	}
	
	// Check if host is online (has WebSocket connection)
	if h.wsHandler == nil || !h.wsHandler.IsHostOnline(req.DeviceID) {
		log.Printf("Auth verify failed: device %s is offline", req.DeviceID)
		c.JSON(http.StatusOK, gin.H{
			"valid":   false,
			"error":   "HOST_OFFLINE",
			"message": "设备不在线",
		})
		return
	}
	
	// Verify password
	if !h.authService.VerifyDevice(c.Request.Context(), req.DeviceID, req.Password) {
		log.Printf("Auth verify failed: invalid password for device %s", req.DeviceID)
		c.JSON(http.StatusOK, gin.H{
			"valid":   false,
			"error":   "INVALID_PASSWORD",
			"message": "密码错误",
		})
		return
	}
	
	// Generate connection token (simple implementation for now)
	token := generateRandomHex(16)
	
	log.Printf("Auth verify success: device %s", req.DeviceID)
	c.JSON(http.StatusOK, gin.H{
		"valid":            true,
		"connection_token": token,
	})
}

// GetDeviceStatus handles GET /api/v1/devices/:device_id/status
func (h *APIHandler) GetDeviceStatus(c *gin.Context) {
	deviceID := c.Param("device_id")
	
	// Check if host is online
	online := h.wsHandler != nil && h.wsHandler.IsHostOnline(deviceID)
	
	c.JSON(http.StatusOK, gin.H{
		"device_id": deviceID,
		"online":    online,
	})
}

// Health check endpoint
func (h *APIHandler) HealthCheck(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"status":  "ok",
		"service": "quickdesk-signaling",
	})
}
